name: hackverse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dio: ^5.1.0
  injectable: ^2.1.1
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  palette_generator: ^0.3.3+2
  device_frame: ^1.1.0
  anim_search_bar: ^2.0.3
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
  firebase_auth:
  fluttertoast:
  provider:
  email_validator: ^2.1.16
  flutter_staggered_grid_view: ^0.5.0
  url_launcher: ^6.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/cash/
